#!/bin/bash
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

LAST_UPDATE=`git log -1 | grep Date | cut -c9-`
cat << EOF > js/version.js
function version()
{
    document.write("version: `git describe` / last update: $LAST_UPDATE");
}
EOF
